### ISSUE TITLE
Design the timeline for the Northern Powerhouse display

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/TextAdventureTime#24]
Get in touch with C3 http://c3imaging.com/c3imaging-liverpool/ and Mark Murphy when the Print is ready to go

**Comment by hwayounggit** [comment]
Hey Ross, I'm doing the layout and I'm having trouble working with your file. I think it's because it's an older version. I can't copy your text. Do you have it anywhere else as a text file? I've decided to work on it in InDesign. It's much easier for me to work with and I can get super anal about measurement. Can you also let me know if the 3mm thickness of the vitrines is eating into the additional layer or if it's outside of it? I can create the files in InDesign and output into .pdf and it will be easier if there are further edits down the line. Have to say your .ai file is super helpful.

**Comment by cheapjack** [comment]
It's made in non-el-capitan CS4 so might be why. Im going to leave the `.ai` where it is now and refer from that for my ref. if youre going into InDesign: not going there sorry! 

The vitrines are actually 5mm thick: I just approximated the thickness with 10pt stroke; it should be 14pt.

The vitrine box measurements (the actual path not the inner stroke edges) in the artwork are the actual internal dimensions of the vitrine Ive requested therefore the artwork panels should be the same as those dimensions but if we allow a little more we can trim them exact in case of variation in the vitrines; does that make sense?

I've updated the [DisplayText.md](https://github.com/cheapjack/TextAdventureTime/blob/master/MakeFiles/DisplayText.md) file with the final text so you could copy from the [raw file](https://raw.githubusercontent.com/cheapjack/TextAdventureTime/master/MakeFiles/DisplayText.md) to bring into InDesign. 

Have to say though turning it into InDesign does sound like re-doing all the layout! Watch those hours! Ive also updated the `.svg` [version](https://github.com/cheapjack/TextAdventureTime/blob/master/MakeFiles/TextAdventureArtEFakeLayoutRevised.svg) of the file, mainly as github renders a preview of it: don't know if InDesign could import that but double-check for scaling errors if it does work.

**Comment by cheapjack** [comment]
Ignore the `.svg` file something wrong with it now so going to remove from the repo
